### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat '/Users/nrajlich/GitHub/TooTallNate/now-proxy/deploy'

### ISSUE THREAD

**Issue by antimatter15** [TooTallNate/now-proxy#1]
I ran "npm install -g now-proxy" and it's giving this error:

`Error: ENOENT: no such file or directory, lstat '/Users/nrajlich/GitHub/TooTallNate/now-proxy/deploy'`

It seems that Babel is inlining the "__dirname" declaration in the compilation step.

**Comment by TooTallNate** [comment]
D'oh! Nice find. Will fix ASAP.

**Comment by TooTallNate** [comment]
Please give `v1.0.1` a try!
